version: '3'

services:
  web:
    container_name: uas_ml_web
    build: .
    restart: always
    command: python app.py
    ports:
      - "5005:5005"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    container_name: uas_ml_db
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: